controllers/ExportController.php
<?php
namespace app_simka\controllers;

use Yii;
use technosmart\yii\web\Controller;
use app_simka\models\User;
use app_simka\models\Pegawai;
use app_simka\models\PegawaiAnak;
use app_simka\models\PegawaiDiklat;
use app_simka\models\PegawaiHukumanDisiplin;
use app_simka\models\PegawaiKenaikanGajiBerkala;
use app_simka\models\PegawaiKepangkatan;
use app_simka\models\PegawaiKunjunganLuarNegeri;
use app_simka\models\PegawaiKursusPelatihan;
use app_simka\models\PegawaiMasaPersiapanPensiun;
use app_simka\models\PegawaiMutasi;
use app_simka\models\PegawaiOrganisasi;
use app_simka\models\PegawaiPelaksana;
use app_simka\models\PegawaiPemberhentian;
use app_simka\models\PegawaiPendidikan;
use app_simka\models\PegawaiPenetapanAngkaKredit;
use app_simka\models\PegawaiPenghargaan;
use app_simka\models\PegawaiSaudaraKandung;
use app_simka\models\Kehadiran;
use app_simka\models\Agama;
use app_simka\models\BentukWajah;
use app_simka\models\Eselon;
use app_simka\models\Grade;
use app_simka\models\JenisHukumanDisiplin;
use app_simka\models\JenisJabatan;
use app_simka\models\JenisPemberhentian;
use app_simka\models\JenisSk;
use app_simka\models\JenisUnitKerja;
use app_simka\models\JenjangJabatan;
use app_simka\models\JenjangPendidikan;
use app_simka\models\Kecamatan;
use app_simka\models\KedudukanPegawai;
use app_simka\models\Kelurahan;
use app_simka\models\Kepangkatan;
use app_simka\models\KotaKabupaten;
use app_simka\models\ModelRambut;
use app_simka\models\Negara;
use app_simka\models\Pekerjaan;
use app_simka\models\Provinsi;
use app_simka\models\StatusKepegawaian;
use app_simka\models\StatusMarital;
use app_simka\models\TingkatHukumanDisiplin;
use app_simka\models\UnitKerja;
use app_simka\models\WarnaKulit;
use app_simka\models\FilterKehadiran;
use app_simka\models\BuktiKehadiran;
use app_simka\models\BuktiKehadiranPegawai;
use app_simka\models\FilterProsesManualKehadiran;

class ExportController extends Controller
{
	public function behaviors()
    {
        return [
            'access' => $this->access([
                ['*', true, ['export']]
            ]),
        ];
    }

    public function actionDatatablesTunkin($bulan, $tahun)
    {
        $subQuery = new \yii\db\Query();
        $subQuery
            ->select([
                'p.id',
                'sk.status_kepegawaian as status_kepegawaian',
                'CONCAT("", p.tunkin_nip) as nip',
                'p.tunkin_nama',
                'CONCAT(kp.golongan, "/", kp.ruang) AS kepangkatan',
                'CONCAT("") AS keterangan',
                'g.grade',
                '(g.nominal_tunkin * sk.pajak_tunkin / 100) as nominal_tunkin',
                'g.pajak_tunkin',
                'LEAST(
                    SUM(CASE
                        WHEN kh.potongan_tunkin_persen IS NOT NULL THEN potongan_tunkin_persen
                        WHEN kh.potong_tunkin = "Tidak" THEN 0
                        WHEN k.jadwal_masuk IS NOT NULL AND k.jadwal_pulang IS NOT NULL AND DATE_FORMAT(k.waktu_masuk, "%Y-%m-%d %H:%i") > ADDTIME(k.jadwal_masuk, SEC_TO_TIME(fleksi_time*60)) THEN 2
                        WHEN k.jadwal_masuk IS NOT NULL AND k.jadwal_pulang IS NOT NULL THEN
                            LEAST((TIME_TO_SEC(
                                GREATEST(
                                    TIMEDIFF(
                                        GREATEST(
                                            TIMEDIFF(
                                                IFNULL(DATE_FORMAT(k.waktu_masuk, "%Y-%m-%d %H:%i"), k.jadwal_pulang),
                                                k.jadwal_masuk
                                            ),
                                            0
                                        ),
                                        IFNULL(
                                            GREATEST(
                                                TIMEDIFF(
                                                    CASE WHEN DATE_FORMAT(k.waktu_pulang, "%Y-%m-%d %H:%i") > ADDTIME(k.jadwal_pulang, SEC_TO_TIME(fleksi_time*60)) THEN ADDTIME(k.jadwal_pulang, SEC_TO_TIME(fleksi_time*60)) ELSE DATE_FORMAT(k.waktu_pulang, "%Y-%m-%d %H:%i") END,
                                                    k.jadwal_pulang
                                                ),
                                                0
                                            ),
                                            0
                                        )
                                    ),
                                    "00:00:00"
                                )
                            ) - 1 + 30 * 60) DIV (30 * 60) * 0.5, 2)
                        ELSE 0
                    END) +
                    SUM(CASE
                        WHEN kh.potongan_tunkin_persen IS NOT NULL THEN 0
                        WHEN kh.potong_tunkin = "Tidak" THEN 0
                        WHEN k.jadwal_masuk IS NOT NULL AND k.jadwal_pulang IS NOT NULL THEN
                            LEAST((TIME_TO_SEC(
                                GREATEST(
                                    TIMEDIFF(
                                        k.jadwal_pulang,
                                        IFNULL(
                                            DATE_FORMAT(k.waktu_pulang, "%Y-%m-%d %H:%i"),
                                            k.jadwal_masuk
                                        )
                                    ),
                                    "00:00:00"
                                )
                            ) - 1 + 30 * 60) DIV (30 * 60) * 0.5, 2)
                        ELSE 0
                    END)
                , 100) AS potongan_tunkin',
                'CONCAT("", p.tunkin_nomor_rekening) as tunkin_nomor_rekening',
            ])
            ->from('pegawai p')
            ->join('LEFT JOIN', 'kepangkatan kp', 'kp.id = p.kepangkatan')
            ->join('LEFT JOIN', 'grade g', 'g.id = p.grade')
            ->join('LEFT JOIN', 'status_kepegawaian sk', 'sk.id = p.status_kepegawaian')
            ->join('LEFT JOIN', 'kehadiran k', 'k.pegawai = p.id')
            ->join('LEFT JOIN', 'keterangan_kehadiran kh', 'kh.id = k.keterangan')
            ->join('LEFT JOIN', 'unit_kerja uk', 'uk.id = p.unit_kerja')
            ->where([
                // 'p.id' => $idPegawai,
                'MONTH(k.tanggal)' => $bulan,
                'YEAR(k.tanggal)' => $tahun,
            ])
            ->andWhere(['or',
                ['p.status_kepegawaian' => 1],
                ['p.status_kepegawaian' => 2],
                ['p.status_kepegawaian' => 3],
                ['p.status_kepegawaian' => 5],
                ['p.status_kepegawaian' => 6],
            ])
            ->groupBy(['p.id'])
        ;

        $query = new \yii\db\Query();
        $query
            ->select([
                'id',
                'status_kepegawaian',
                'nip',
                'tunkin_nama',
                'kepangkatan',
                'keterangan',
                'grade',
                'round(nominal_tunkin) AS nominal_tunkin',
                'potongan_tunkin',
                'round(@nilai_pemotongan := (potongan_tunkin / 100 * nominal_tunkin)) AS nilai_pemotongan',
                'round(@jumlah_pemotongan := (nominal_tunkin - @nilai_pemotongan)) AS jumlah_pemotongan',
                'round(@pajak_pegawai := (@jumlah_pemotongan * pajak_tunkin / 100)) AS pajak_pegawai',
                'round(@bruto := (@pajak_pegawai + @jumlah_pemotongan)) AS bruto',
                'round(@pajak_pegawai) AS potongan_pajak',
                'round(@bruto - @pajak_pegawai) AS netto',
                'tunkin_nomor_rekening',
            ])
            ->from(['sq' => $subQuery])
        ;
        
        return $this->datatables($query, Yii::$app->request->post(), Pegawai::getDb());
    }

    public function actionTunkin($id = null, $tab = 'jabatan', $bulan = null, $tahun = null)
    {
        $model['filter_kehadiran'] = new FilterKehadiran();
        if ($bulan) {
            $model['filter_kehadiran']->bulan = $bulan;
        }
        if ($tahun) {
            $model['filter_kehadiran']->tahun = $tahun;
        }

        if (!$id) {
            return $this->render('list-tunkin', [
                'model' => $model,
                'title' => 'Daftar Tunjangan Kinerja Pegawai',
            ]);
        }
    }

    public function actionTunkinUpdate($id, $tab = 'tunkin')
    {
        $error = true;

        if (isset($id)) {
            if (($model['pegawai'] = Pegawai::find()->where(['id' => $id])->one()) == null) {
                throw new \yii\web\HttpException(404, 'The requested page does not exist.');
            }
        } else {
            $model['user'] = new User(['scenario' => 'password']);
            $model['pegawai'] = new Pegawai();
        }

        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();

            $model['pegawai']->load($post);
            if (false) {
                if (isset($post['PegawaiAnak'])) {
                    foreach ($post['PegawaiAnak'] as $key => $value) {
                        if ($value['id'] > 0) {
                            $pegawaiAnak = PegawaiAnak::find()->where(['id' => $value['id']])->one();
                            $pegawaiAnak->setAttributes($value);
                        } else if($value['id'] < 0) {
                            $pegawaiAnak = PegawaiAnak::find()->where(['id' => $value['id']*-1])->one();
                            $pegawaiAnak->isDeleted = true;
                        } else {
                            $pegawaiAnak = new PegawaiAnak();
                            $pegawaiAnak->setAttributes($value);
                        }
                        $pegawaiAnak->index = $key;
                        $model['pegawai_anak'][] = $pegawaiAnak;
                    }
                }
                if (isset($post['PegawaiDiklat'])) {

views/export/list-master.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

$this->registerJsFile('@web/app/export/list-master-grade.js', ['depends' => 'technosmart\assets_manager\DatatablesAsset']);
$this->registerJsFile('@web/app/export/list-master-kepangkatan.js', ['depends' => 'technosmart\assets_manager\DatatablesAsset']);
$this->registerJsFile('@web/app/export/list-master-status-kepegawaian.js', ['depends' => 'technosmart\assets_manager\DatatablesAsset']);
?>

<div class="box box-break-sm box-space-md box-gutter box-equal">
    <div class="box-12 bg-lightest shadow-bottom-right rounded-xs padding-x-30 m-padding-x-15 padding-y-15 border-azure border-thin rounded-md">
        <div class="tab-wrapper">
            <ul class="tab-menu tab-menu-selector">
                <li><a href="#grade" class="<?= $tab == 'grade' ? 'active' : '' ?>">Grade</a></li>
                <li><a href="#kepangkatan" class="<?= $tab == 'kepangkatan' ? 'active' : '' ?>">Kepangkatan</a></li>
                <li><a href="#status-kepegawaian" class="<?= $tab == 'status-kepegawaian' ? 'active' : '' ?>">Status Kepegawaian</a></li>
            </ul>
            <div id="grade" class="tab-content">
                <div class="padding-x-30 m-padding-x-15 padding-y-15">
                    <div>
                        <div class="clearfix">
                            <span class="fs-16 text-azure fs-italic">Daftar Grade</span>
                            <?= Html::a('Tambah Data', ['master-form', 'tab' => 'grade'], ['class' => 'button pull-right m-pull-none m-button-block bg-azure border-azure']) ?>
                        </div>
                        <hr class="margin-y-10 border-top border-light-orange">

                        <table class="datatables-master-grade table table-nowrap">
                            <thead>
                                <tr class="text-dark">
                                    <th style="width:50px;"></th>
                                    <th>Grade</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
            <div id="kepangkatan" class="tab-content">
                <div class="padding-x-30 m-padding-x-15 padding-y-15">
                    <div>
                        <div class="clearfix">
                            <span class="fs-16 text-azure fs-italic">Daftar Kepangkatan</span>
                            <?= Html::a('Tambah Data', ['master-form', 'tab' => 'kepangkatan'], ['class' => 'button pull-right m-pull-none m-button-block bg-azure border-azure']) ?>
                        </div>
                        <hr class="margin-y-10 border-top border-light-orange">

                        <table class="datatables-master-kepangkatan table table-nowrap">
                            <thead>
                                <tr class="text-dark">
                                    <th style="width:50px;"></th>
                                    <th>Pangkat</th>
                                    <th>Golongan</th>
                                    <th>Ruang</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
            <div id="status-kepegawaian" class="tab-content">
                <div class="padding-x-30 m-padding-x-15 padding-y-15">
                    <div>
                        <div class="clearfix">
                            <span class="fs-16 text-azure fs-italic">Daftar Status Kepegawaian</span>
                            <?= Html::a('Tambah Data', ['master-form', 'tab' => 'status-kepegawaian'], ['class' => 'button pull-right m-pull-none m-button-block bg-azure border-azure']) ?>
                        </div>
                        <hr class="margin-y-10 border-top border-light-orange">

                        <table class="datatables-master-status-kepegawaian table table-nowrap">
                            <thead>
                                <tr class="text-dark">
                                    <th style="width:50px;"></th>
                                    <th>Status Kepegawaian</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/export/list-tunkin.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

$this->registerJsFile('@web/app/export/list-tunkin1.js', ['depends' => 'technosmart\assets_manager\DatatablesAsset']);

$this->registerJs(
    'var tahun = ' . json_encode($model['filter_kehadiran']->tahun) . ';' .
    'var bulan = ' . json_encode($model['filter_kehadiran']->bulan) . ';' .
    '',
    3
);

$bulans = ['01' => 'Januari', '02' => 'Februari', '03' => 'Maret', '04' => 'April', '05' => 'Mei', '06' => 'Juni', '07' => 'Juli', '08' => 'Agustus', '09' => 'September', '10' => 'Oktober', '11' => 'November', '12' => 'Desember', ];
$tahuns = ['2019' => '2019', '2020' => '2020', '2021' => '2021', '2022' => '2022', '2023' => '2023', '2024' => '2024', ];
?>

<div class="box box-break-sm box-space-md box-gutter box-equal">
    <div class="box-12 bg-lightest shadow-bottom-right rounded-xs padding-x-30 m-padding-x-15 padding-y-15 border-azure border-thin rounded-md">
        <div class="clearfix">
            <span class="fs-18 text-azure fs-italic">Kelola Data Pegawai</span>
            <?php if ($this->context->can('create')): ?>
        <?php endif; ?>
        </div>
        <hr class="margin-y-10 border-top border-light-orange">

        <?php $form = ActiveForm::begin([/*'enableClientValidation' => true, */'options' => ['id' => 'app'], 'method' => 'get', 'action' => Url::to(['export/tunkin'])]); ?>
            <div class="box box-break-md box-gutter">
                <div class="box-2">
                    <?= $form->field($model['filter_kehadiran'], 'bulan', ['options' => ['class' => 'form-wrapper margin-0'], 'selectors' => ['error' => '.form-info']])->begin(); ?>
                        <?= Html::activeDropDownList($model['filter_kehadiran'], 'bulan', $bulans, ['class' => 'form-dropdown', 'name' => 'bulan']); ?>
                    <?= $form->field($model['filter_kehadiran'], 'bulan')->end(); ?>
                </div>
                <div class="box-2">
                    <?= $form->field($model['filter_kehadiran'], 'tahun', ['options' => ['class' => 'form-wrapper margin-0'], 'selectors' => ['error' => '.form-info']])->begin(); ?>
                        <?= Html::activeDropDownList($model['filter_kehadiran'], 'tahun', $tahuns, ['class' => 'form-dropdown', 'name' => 'tahun']); ?>
                    <?= $form->field($model['filter_kehadiran'], 'tahun')->end(); ?>
                </div>
                <div class="box-2">
                    <div class="form-wrapper margin-0">
                        <button class="button button-block border-azure bg-azure m-margin-top-5" type="submit">Tampilkan</button>
                    </div>
                </div>
            </div>
        <?php ActiveForm::end(); ?>

        <hr class="margin-y-10 border-top border-light-orange">

        <div class="scroll-x">
            <table class="datatables-tunkin table table-nowrap">
                <thead>
                    <tr class="text-dark">
                        <th></th>
                        <th>Status</th>
                        <th>Nip</th>
                        <th>Nama</th>
                        <th>Golongan</th>
                        <th>Keterangan</th>
                        <th>Grade</th>
                        <th>Tunjangan</th>
                        <th>Potongan</th>
                        <th>Nilai Pemotongan</th>
                        <th>Jumlah Pemotongan</th>
                        <th>Pajak Pegawai</th>
                        <th>Bruto</th>
                        <th>Potongan Pajak</th>
                        <th>Netto</th>
                        <th>Nomor Rekening</th>
                    </tr>
                    <tr class="dt-search">
                        <th></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search status..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search nip..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search nama..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search golongan..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search keterangan..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search grade..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search tunjangan..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search potongan..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search nilai pemotongan..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search jumlah pemotongan..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search pajak pegawai..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search bruto..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search potongan pajak..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search netto..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search nomor rekening..."/></th>
                </thead>
            </table>
        </div>
    </div>
</div>

views/export/list-uang-makan.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

if (isset($title)) $this->title = $title;
if (isset($subtitle)) $this->subtitle = $subtitle;
if (isset($breadcrumbs)) $this->params['breadcrumbs'] = $breadcrumbs;

$this->registerJsFile('@web/app/export/list-uang-makan.js', ['depends' => 'technosmart\assets_manager\DatatablesAsset']);

$this->registerJs(
    'var tahun = ' . json_encode($model['filter_kehadiran']->tahun) . ';' .
    'var bulan = ' . json_encode($model['filter_kehadiran']->bulan) . ';' .
    '',
    3
);

$bulans = ['01' => 'Januari', '02' => 'Februari', '03' => 'Maret', '04' => 'April', '05' => 'Mei', '06' => 'Juni', '07' => 'Juli', '08' => 'Agustus', '09' => 'September', '10' => 'Oktober', '11' => 'November', '12' => 'Desember', ];
$tahuns = ['2019' => '2019', '2020' => '2020', '2021' => '2021', '2022' => '2022', '2023' => '2023', '2024' => '2024', ];

$query = new \yii\db\Query();
$query
    ->select([
        'uk.unit_kerja',
    ])
    ->from('unit_kerja uk')
;
$pilihanUnitKerja = $query->all();
?>

<div class="box box-break-sm box-space-md box-gutter box-equal">
    <div class="box-12 bg-lightest shadow-bottom-right rounded-xs padding-x-30 m-padding-x-15 padding-y-15 border-azure border-thin rounded-md">
        <div class="clearfix">
            <span class="fs-18 text-azure fs-italic">Daftar Uang Makan</span>
        </div>
        <hr class="margin-y-10 border-top border-light-orange">

        <?php $form = ActiveForm::begin([/*'enableClientValidation' => true, */'options' => ['id' => 'app'], 'method' => 'get', 'action' => Url::to(['export/uang-makan'])]); ?>
            <div class="box box-break-md box-gutter">
                <div class="box-2">
                    <?= $form->field($model['filter_kehadiran'], 'bulan', ['options' => ['class' => 'form-wrapper margin-0'], 'selectors' => ['error' => '.form-info']])->begin(); ?>
                        <?= Html::activeDropDownList($model['filter_kehadiran'], 'bulan', $bulans, ['class' => 'form-dropdown', 'name' => 'bulan']); ?>
                    <?= $form->field($model['filter_kehadiran'], 'bulan')->end(); ?>
                </div>
                <div class="box-2">
                    <?= $form->field($model['filter_kehadiran'], 'tahun', ['options' => ['class' => 'form-wrapper margin-0'], 'selectors' => ['error' => '.form-info']])->begin(); ?>
                        <?= Html::activeDropDownList($model['filter_kehadiran'], 'tahun', $tahuns, ['class' => 'form-dropdown', 'name' => 'tahun']); ?>
                    <?= $form->field($model['filter_kehadiran'], 'tahun')->end(); ?>
                </div>
                <div class="box-2">
                    <div class="form-wrapper margin-0">
                        <button class="button button-block border-azure bg-azure m-margin-top-5" type="submit">Tampilkan</button>
                    </div>
                </div>
            </div>
        <?php ActiveForm::end(); ?>

        <hr class="margin-y-10 border-top border-light-orange">

        <div class="scroll-x">
            <table class="datatables-kehadiran-bulanan table table-nowrap">
                <thead>
                    <tr class="text-dark">
                        <th>Nama<br>Pegawai</th>
                        <th>NIP<br>Pegawai</th>
                        <th>Unit<br>Kerja</th>
                        <th>Total<br>Kehadiran</th>
                        <th>Total<br>Ketidakhadiran</th>
                    </tr>
                    <tr class="dt-search">
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search nama..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search nip..."/></th>
                        <th><input type="text" class="form-text border-none padding-0" placeholder="search unit kerja..." list="unitKerja"/>
                            <datalist id="unitKerja">
                                <?php foreach ($pilihanUnitKerja as $key => $value) : ?>
                                    <option value="<?= $value['unit_kerja'] ?>">
                                <?php endforeach; ?>
                            </datalist>
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>